INSERT INTO cid_cidade (cid_descricao) VALUES ('ADAMANTINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ADOLFO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AGISSE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ÁGUA VERMELHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AGUAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ÁGUAS DA PRATA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ÁGUAS DE LINDÓIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ÁGUAS DE SANTA BÁRBARA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ÁGUAS DE SÃO PEDRO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AGUDOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AGULHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AJAPI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALAMBARI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALBERTO MOREIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALDEIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALDEIA DE CARAPICUÍBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALFREDO GUEDES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALFREDO MARCONDES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALTAIR');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALTINÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALTO ALEGRE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALTO PORÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALUMÍNIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ÁLVARES FLORENCE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ÁLVARES MACHADO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ÁLVARO DE CARVALHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ALVINLÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AMADEU AMARAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AMANDABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AMELIÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AMERICANA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AMÉRICO BRASILIENSE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AMÉRICO DE CAMPOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AMPARO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ANA DIAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ANALÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ANÁPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ANDES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ANDRADINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ANGATUBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ANHEMBI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ANHUMAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ANHUMAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('APARECIDA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('APARECIDA D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('APARECIDA DE MONTE ALTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('APARECIDA DE SÃO MANUEL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('APARECIDA DO BONITO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('APIAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('APIAÍ-MIRIM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARABELA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARACAÇU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARAÇAÍBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARAÇARIGUAMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARAÇATUBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARAÇOIABA DA SERRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARAMINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARANDU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARAPEÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARARAQUARA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARARAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARAXÁS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARCADAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARCO-ÍRIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AREALVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AREIAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AREIÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARIRANHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARIRI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARTEMIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARTUR NOGUEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ARUJÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ASPÁSIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ASSIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ASSISTÊNCIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ATIBAIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ATLÂNTIDA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AURIFLAMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AVAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AVANHANDAVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AVARÉ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('AVENCAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BACAETAVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BACURITI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BADY BASSITT');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BAGUAÇU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BAIRRO ALTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BALBINOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BÁLSAMO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BANANAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BANDEIRANTES D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARÃO ATALIBA NOGUEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARÃO DE ANTONINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARÃO DE GERALDO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARBOSA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARIRI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARRA BONITA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARRA DO CHAPÉU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARRA DO TURVO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARRA DOURADA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARRÂNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARRETOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARRINHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BARUERI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BASTOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BATATAIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BATATUBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BATISTA BOTELHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BAURU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BEBEDOURO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BELA FLORESTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BELA VISTA SÃO-CARLENSE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BENTO DE ABREU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BERNARDINO DE CAMPOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BERTIOGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BILAC');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BIRIGÜI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BIRITIBA-MIRIM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BIRITIBA-USSU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOA ESPERANÇA DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOA VISTA DOS ANDRADAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOA VISTA PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOCAINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOFETE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOITUVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOM FIM DO BOM JESUS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOM JESUS DOS PERDÕES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOM RETIRO DA ESPERANÇA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOM SUCESSO DE ITARARÉ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BONFIM PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BORÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BORACÉIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BORBOREMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOREBI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOTAFOGO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOTELHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOTUCATU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BOTUJURU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BRAÇO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BRAGANÇA PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BRÁS CUBAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BRASITÂNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BRAÚNA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BREJO ALEGRE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BRODOWSKI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BROTAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BUENO DE ANDRADA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BURI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BURITAMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('BURITIZAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CABRÁLIA PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CABREÚVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAÇAPAVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CACHOEIRA DE EMAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CACHOEIRA PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CACONDE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAFELÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAFESÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAIABU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAIBURA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAIEIRAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAIUÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAJAMAR');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAJATI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAJOBI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAJURU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAMBAQUARA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAMBARATIBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAMPESTRINHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAMPINA DE FORA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAMPINA DO MONTE ALEGRE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAMPINAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAMPINAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAMPO LIMPO PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAMPOS DE CUNHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAMPOS DO JORDÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAMPOS NOVOS PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CANANÉIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CANAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CANDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CÂNDIDO MOTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CÂNDIDO RODRIGUES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CANGUERA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CANITAR');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAPÃO BONITO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAPELA DO ALTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAPIVARI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAPIVARI DA MATA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAPORANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAPUAVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CARAGUATATUBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CARAPICUÍBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CARDEAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CARDOSO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CARDOSO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CARUARA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CASA BRANCA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CÁSSIA DOS COQUEIROS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CASTILHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CATANDUVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CATIGUÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CATUCABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CAUCAIA DO ALTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CEDRAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CERQUEIRA CÉSAR');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CERQUILHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CESÁRIO LANGE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CEZAR DE SOUZA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CHARQUEADA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CHAVANTES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CIPÓ-GUAÇU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CLARINIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CLEMENTINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('COCAES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('COLINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('COLÔMBIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CONCEIÇÃO DE MONTE ALEGRE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CONCHAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CONCHAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CORDEIRÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('COROADOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CORONEL GOULART');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CORONEL MACEDO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CORREDEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CÓRREGO RICO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CORUMBATAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('COSMÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('COSMORAMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('COSTA MACHADO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('COTIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CRAVINHOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CRISTAIS PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CRUZ DAS POSSES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CRUZÁLIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CRUZEIRO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CUBATÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CUIABÁ PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CUNHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('CURUPÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DALAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DESCALVADO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DIADEMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DIRCE REIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DIRCEU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DIVINOLÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DOBRADA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DOIS CÓRREGOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DOLCINÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DOMÉLIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DOURADO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DRACENA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DUARTINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DUMONT');
INSERT INTO cid_cidade (cid_descricao) VALUES ('DUPLO CÉU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ECHAPORÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ELDORADO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ELEUTÉRIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ELIAS FAUSTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ELISIÁRIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('EMBAÚBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('EMBU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('EMBU-GUAÇU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('EMILIANÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ENEIDA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ENGENHEIRO BALDUÍNO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ENGENHEIRO COELHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ENGENHEIRO MAIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ENGENHEIRO SCHMIDT');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ESMERALDA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ESPERANÇA D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ESPIGÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ESPÍRITO SANTO DO PINHAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ESPÍRITO SANTO DO TURVO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ESTIVA GERBI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ESTRELA D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ESTRELA DO NORTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('EUCLIDES DA CUNHA PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('EUGÊNIO DE MELO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FARTURA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FÁTIMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FÁTIMA PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FAZENDA VELHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FERNANDO PRESTES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FERNANDÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FERNÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FERRAZ DE VASCONCELOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FLORA RICA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FLOREAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FLORESTA DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FLÓRIDA PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FLORÍNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FRANCA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FRANCISCO MORATO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FRANCO DA ROCHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('FRUTAL DO CAMPO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GABRIEL MONTEIRO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GÁLIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GARÇA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GARDÊNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GASTÃO VIDIGAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GAVIÃO PEIXOTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GENERAL SALGADO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GETULINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GLICÉRIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GRAMADINHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUACHOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUAIANAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUAIÇARA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUAIMBÊ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUAÍRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUAMIUM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUAPIAÇU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUAPIARA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUAPIRANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARAÇAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARACI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARACIABA D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARANI D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARANTÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARAPIRANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARAPUÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARARAPES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARAREMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARATINGUETÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUAREÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARIBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARIROBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARIZINHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARUJÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUARULHOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUATAPARÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('GUZOLÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('HERCULÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('HOLAMBRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('HOLAMBRA II');
INSERT INTO cid_cidade (cid_descricao) VALUES ('HORTOLÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IACANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IACRI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IARAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IBATÉ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IBIPORANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IBIRÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IBIRAREMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IBITINGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IBITIRUNA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IBITIÚVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IBITU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IBIÚNA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ICÉM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IDA IOLANDA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IEPÊ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IGAÇABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IGARAÇU DO TIETÊ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IGARAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IGARAPAVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IGARATÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IGUAPE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ILHA COMPRIDA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ILHA DIANA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ILHA SOLTEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ILHABELA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('INDAIÁ DO AGUAPEÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('INDAIATUBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('INDIANA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('INDIAPORÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('INGÁS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('INÚBIA PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IPAUSSU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IPERÓ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IPEÚNA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IPIGUÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IPORANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IPUÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IRACEMÁPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IRAPÉ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IRAPUÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IRAPURU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITABERÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITABOA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAIUBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAJOBI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAJU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITANHAÉM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAÓCA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAPECERICA DA SERRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAPETININGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAPEUNA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAPEVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAPEVI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAPIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAPIRAPUÃ PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITÁPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAPORANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAPUÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAPURA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAQUAQUECETUBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITAQUERI DA SERRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITARARÉ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITARIRI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITATIBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITATINGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITIRAPINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITIRAPUÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITOBI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITORORÓ DO PARANAPANEMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITUPEVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ITUVERAVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('IUBATINGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JABORANDI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JABOTICABAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JACARÉ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JACAREÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JACI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JACIPORÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JACUBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JACUPIRANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JAFA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JAGUARIÚNA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JALES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JAMAICA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JAMBEIRO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JANDIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JARDIM BELVAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JARDIM PRESIDENTE DUTRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JARDIM SANTA LUZIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JARDIM SILVEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JARDINÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JARINU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JATOBÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JAÚ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JERIQUARA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JOANÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JOÃO RAMALHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JOAQUIM EGÍDIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JORDANÉSIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JOSÉ BONIFÁCIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JULIÂNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JÚLIO MESQUITA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JUMIRIM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JUNDIAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JUNDIAPEBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JUNQUEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JUNQUEIRÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JUQUIÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JUQUIRATIBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JUQUITIBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JURITIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JURUCÊ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JURUPEBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('JURUPEMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LÁCIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LAGOA AZUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LAGOA BRANCA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LAGOINHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LARANJAL PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LARAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LAURO PENTEADO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LAVÍNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LAVRINHAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LEME');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LENÇÓIS PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LIMEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LINDÓIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LINS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LOBO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LORENA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LOURDES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LOUVEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LUCÉLIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LUCIANÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LUÍS ANTÔNIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LUIZIÂNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LUPÉRCIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LUSITÂNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('LUTÉCIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MACATUBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MACAUBAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MACEDÔNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MACUCOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MÁGDA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MAILASQUI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MAIRINQUE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MAIRIPORÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MAJOR PRADO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MANDURI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MANGARATU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARABÁ PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARACAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARAPOAMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARCONDÉSIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARESIAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARIÁPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARÍLIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARINÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARISTELA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARTIM FRANCISCO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARTINHO PRADO JÚNIOR');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MARTINÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MATÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MAUÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MENDONÇA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MERIDIANO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MESÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MIGUELÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MINEIROS DO TIETÊ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MIRA ESTRELA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MIRACATU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MIRALUZ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MIRANDÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MIRANTE DO PARANAPANEMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MIRASSOL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MIRASSOLÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MOCOCA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MOGI DAS CRUZES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MOGI GUAÇU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MOGI MIRIM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MOMBUCA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONÇÕES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONGAGUÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONTALVÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONTE ALEGRE DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONTE ALTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONTE APRAZÍVEL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONTE AZUL PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONTE CABRÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONTE CASTELO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONTE MOR');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONTE VERDE PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MONTEIRO LOBATO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MOREIRA CÉSAR');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MORRO AGUDO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MORRO DO ALTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MORUNGABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MOSTARDAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MOTUCA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MOURÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('MURUTINGA DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NANTES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NARANDIBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NATIVIDADE DA SERRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NAZARÉ PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NEVES PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NHANDEARA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NIPOÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOGUEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOSSA SENHORA DO REMÉDIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA ALEXANDRIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA ALIANÇA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA AMÉRICA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA APARECIDA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA CAMPINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA CANAÃ PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA CASTILHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA EUROPA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA GRANADA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA GUATAPORANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA INDEPENDÊNCIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA ITAPIREMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA LUZITÂNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA ODESSA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA PÁTRIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVA VENEZA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVAIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVO CRAVINHOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NOVO HORIZONTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('NUPORANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('OÁSIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('OCAUÇU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ÓLEO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('OLÍMPIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('OLIVEIRA BARROS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ONDA BRANCA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ONDA VERDE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ORIENTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ORINDIÚVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ORLÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('OSASCO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('OSCAR BRESSANE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('OSVALDO CRUZ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('OURINHOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('OURO FINO PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('OURO VERDE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('OUROESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PACAEMBU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PADRE NÓBREGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PALESTINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PALMARES PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PALMEIRA D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PALMEIRAS DE SÃO PAULO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PALMITAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PANORAMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARAGUAÇU PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARAIBUNA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARAÍSO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARAISOLÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARANABI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARANAPANEMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARANAPIACABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARANAPUÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARAPUÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARDINHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARIQUERA-AÇU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARISI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARNASO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARQUE MEIA LUA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PARURU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PATROCÍNIO PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PAULICÉIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PAULÍNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PAULISTÂNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PAULO DE FARIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PAULÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PEDERNEIRAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PEDRA BELA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PEDRA BRANCA DE ITARARÉ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PEDRANÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PEDREGULHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PEDREIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PEDRINHAS PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PEDRO BARROS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PEDRO DE TOLEDO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PENÁPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PEREIRA BARRETO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PEREIRAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PERUÍBE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIACATU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PICINGUABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIEDADE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PILAR DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PINDAMONHANGABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PINDORAMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PINHALZINHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PINHEIROS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIONEIROS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIQUEROBI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIQUETE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIRACAIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIRACICABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIRAJU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIRAJUÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIRAMBÓIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIRANGI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIRAPITINGUI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIRAPORA DO BOM JESUS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIRAPOZINHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIRASSUNUNGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PIRATININGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PITANGUEIRAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PLANALTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PLANALTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PLANALTO DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PLATINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('POÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('POLONI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('POLVILHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('POMPÉIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PONGAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PONTAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PONTALINDA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PONTES GESTAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('POPULINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PORANGABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PORTO FELIZ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PORTO FERREIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PORTO NOVO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('POTIM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('POTIRENDABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('POTUNDUVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRACINHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRADÍNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRADÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRAIA GRANDE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRATÂNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRESIDENTE ALVES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRESIDENTE BERNARDES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRESIDENTE EPITÁCIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRESIDENTE PRUDENTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRESIDENTE VENCESLAU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRIMAVERA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PROMISSÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('PRUDÊNCIO E MORAES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('QUADRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('QUATÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('QUEIROZ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('QUELUZ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('QUINTANA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('QUIRIRIM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RAFARD');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RANCHARIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RECHAN');
INSERT INTO cid_cidade (cid_descricao) VALUES ('REDENÇÃO DA SERRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('REGENTE FEIJÓ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('REGINÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('REGISTRO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RESTINGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIACHO GRANDE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIBEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIBEIRÃO BONITO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIBEIRÃO BRANCO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIBEIRÃO CORRENTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIBEIRÃO DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIBEIRÃO DOS ÍNDIOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIBEIRÃO GRANDE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIBEIRÃO PIRES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIBEIRÃO PRETO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIBEIRO DO VALE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIBEIRO DOS SANTOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIFAINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RINCÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RINÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIO CLARO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIO DAS PEDRAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIO GRANDE DA SERRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIOLÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RIVERSUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ROBERTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ROSÁLIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ROSANA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ROSEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RUBIÁCEA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RUBIÃO JÚNIOR');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RUBINÉIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('RUILÂNDIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SABAÚNA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SABINO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SAGRES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SALES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SALES OLIVEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SALESÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SALMOURÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SALTINHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SALTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SALTO DE PIRAPORA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SALTO DO AVANHANDAVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SALTO GRANDE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANDOVALINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA ADÉLIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA ALBERTINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA AMÉRICA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA BÁRBARA D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA BRANCA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA CLARA D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA CRUZ DA CONCEIÇÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA CRUZ DA ESPERANÇA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA CRUZ DA ESTRELA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA CRUZ DAS PALMEIRAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA CRUZ DO RIO PARDO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA CRUZ DOS LOPES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA ERNESTINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA EUDÓXIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA FÉ DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA GERTRUDES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA ISABEL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA ISABEL DO MARINHEIRO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA LÚCIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA MARGARIDA PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA MARIA DA SERRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA MARIA DO GURUPÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA MERCEDES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA RITA D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA RITA DO PASSA QUATRO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA RITA DO RIBEIRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA ROSA DE VITERBO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA SALETE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTA TERESINHA DE PIRACICABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTANA DA PONTE PENSA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTANA DE PARNAÍBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTELMO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTO ANASTÁCIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTO ANDRÉ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTO ANTÔNIO DA ALEGRIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTO ANTÔNIO DA ESTIVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTO ANTÔNIO DE POSSE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTO ANTÔNIO DO ARACANGUÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTO ANTÔNIO DO JARDIM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTO ANTÔNIO DO PARANAPANEMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTO ANTÔNIO DO PINHAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTO ANTÔNIO PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTO EXPEDITO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTÓPOLIS DO AGUAPEÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SANTOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO BENEDITO DA CACHOEIRINHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO BENEDITO DAS AREIAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO BENTO DO SAPUCAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO BERNARDO DO CAMPO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO BERTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO CAETANO DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO CARLOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO FRANCISCO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO FRANCISCO DA PRAIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO FRANCISCO XAVIER');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOÃO DA BOA VISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOÃO DAS DUAS PONTES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOÃO DE IRACEMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOÃO DE ITAGUAÇU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOÃO DO MARINHEIRO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOÃO DO PAU D`ALHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOÃO NOVO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOAQUIM DA BARRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOSÉ DA BELA VISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOSÉ DAS LARANJEIRAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOSÉ DO BARREIRO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOSÉ DO RIO PARDO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOSÉ DO RIO PRETO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO JOSÉ DOS CAMPOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO LOURENÇO DA SERRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO LOURENÇO DO TURVO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO LUIZ DO PARAITINGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO LUIZ DO GUARICANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO MANUEL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO MARTINHO D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO MIGUEL ARCANJO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO PAULO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO PEDRO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO PEDRO DO TURVO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO ROQUE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO ROQUE DA FARTURA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO SEBASTIÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO SEBASTIÃO DA GRAMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO SEBASTIÃO DA SERRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO SILVESTRE DE JACAREÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO SIMÃO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SÃO VICENTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SAPEZAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SARAPUÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SARUTAIÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SEBASTIANÓPOLIS DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SERRA AZUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SERRA NEGRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SERRANA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SERTÃOZINHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SETE BARRAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SEVERÍNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SILVÂNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SILVEIRAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SIMÕES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SIMONSEN');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SOCORRO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SODRÉLIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SOLEMAR');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SOROCABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SOUSAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SUD MENNUCCI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SUINANA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SUMARÉ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SUSSUI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SUZANÁPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('SUZANO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TABAJARA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TABAPUÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TABATINGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TABOÃO DA SERRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TACIBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAGUAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAIAÇU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAIACUPEBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAIÚVA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TALHADO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAMBAÚ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TANABI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAPINAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAPIRAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAPIRATIBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAQUARAL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAQUARITINGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAQUARITUBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAQUARIVAÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TARABAI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TARUMÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TATUÍ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TAUBATÉ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TECAINDA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TEJUPÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TEODORO SAMPAIO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TERMAS DE IBIRÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TERRA NOVA D`OESTE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TERRA ROXA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TIBIRIÇÁ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TIBIRIÇÁ DO PARANAPANEMA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TIETÊ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TIMBURI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TOLEDO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TORRE DE PEDRA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TORRINHA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TRABIJU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TREMEMBÉ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TRÊS ALIANÇAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TRÊS FRONTEIRAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TRÊS PONTES');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TRÊS VENDAS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TUIUTI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TUJUGUABA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TUPÃ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TUPI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TUPI PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TURIBA DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TURIÚBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TURMALINA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('TURVÍNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('UBARANA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('UBATUBA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('UBIRAJARA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('UCHOA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('UNIÃO PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('UNIVERSO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('URÂNIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('URU');
INSERT INTO cid_cidade (cid_descricao) VALUES ('URUPÊS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('URURAI');
INSERT INTO cid_cidade (cid_descricao) VALUES ('UTINGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VALE FORMOSO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VALENTIM GENTIL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VALINHOS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VALPARAÍSO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VANGLÓRIA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VARGEM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VARGEM GRANDE DO SUL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VARGEM GRANDE PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VARPA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VÁRZEA PAULISTA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VENDA BRANCA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VERA CRUZ');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VICENTE DE CARVALHO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VICENTINÓPOLIS');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VILA DIRCE');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VILA NERY');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VILA XAVIER');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VINHEDO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VIRADOURO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VISTA ALEGRE DO ALTO');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VITÓRIA BRASIL');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VITORIANA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VOTORANTIM');
INSERT INTO cid_cidade (cid_descricao) VALUES ('VOTUPORANGA');
INSERT INTO cid_cidade (cid_descricao) VALUES ('ZACARIAS');

UPDATE cid_cidade SET cid_uf = 'SP';
